CREATE TABLE Comarca (
    ID SERIAL PRIMARY KEY,
    YEAR NUMERIC NOT NULL,
    CODE NUMERIC NOT NULL,
    NAME VARCHAR NOT NULL,
    POPULATION NUMERIC NOT NULL,
    DOMNET NUMERIC NOT NULL,
    ECOACT NUMERIC NOT NULL,
    TOTAL NUMERIC NOT NULL,
    INDIVIDUALEXP DECIMAL NOT NULL
);